<?php
/**
 * @file
 * Taz Core module.
 */

// Load helper API functions.
module_load_include('module', 'taz_core', 'taz_core.api');

/**
 * Implements hook_admin_paths().
 *
 * Make user pages use admin theme. This is relatively harmless because users
 * have to have the "View the administration theme" permission.
 */
function taz_core_admin_paths() {
  return array(
    'user*' => TRUE,
  );
}

/**
 * Implements hook_admin_paths_alter().
 * A trick to enforce page refresh when theme is changed from an overlay.
 */
function taz_core_admin_paths_alter(&$paths) {
  $paths['admin/appearance/default*'] = FALSE;
}

/**
 * Implements hook_views_api().
 */
function taz_core_views_api() {
  return array('version' => '3.0');
}

/**
 * Implements hook_backup_migrate_profiles().
 */
function taz_core_backup_migrate_profiles() {
  return array(
    'dev_snapshot' => backup_migrate_crud_create_item('profile', array(
      'name' => t("Dev Snapshot"),
      'profile_id' => 'dev_snapshot',
      'filename' => '[site:name]',
      'append_timestamp' => '0',
      'filters' => array(
        'compression' => 'gzip',
        'notify_success_enable' => 0,
        'notify_failure_enable' => 0,
        'utils_site_offline' => 0,
        'utils_site_offline_message' => 'This website is currently under maintenance. We should be back shortly. Thank you for your patience.',
        'utils_description' => '',
        'destinations' => array(
          'db' => array(
            'exclude_tables' => array(),
            'nodata_tables' => array(
              'cache' => 'cache',
              'cache_admin_menu' => 'cache_admin_menu',
              'cache_block' => 'cache_block',
              'cache_bootstrap' => 'cache_bootstrap',
              'cache_field' => 'cache_field',
              'cache_filter' => 'cache_filter',
              'cache_form' => 'cache_form',
              'cache_image' => 'cache_image',
              'cache_l10n_update' => 'cache_l10n_update',
              'cache_libraries' => 'cache_libraries',
              'cache_media_xml' => 'cache_media_xml',
              'cache_menu' => 'cache_menu',
              'cache_page' => 'cache_page',
              'cache_path' => 'cache_path',
              'cache_token' => 'cache_token',
              'cache_update' => 'cache_update',
              'cache_views' => 'cache_views',
              'cache_views_data' => 'cache_views_data',
              'ctools_css_cache' => 'ctools_css_cache',
              'ctools_object_cache' => 'ctools_object_cache',
              'search_dataset' => 'search_dataset',
              'search_index' => 'search_index',
              'search_total' => 'search_total',
              'sessions' => 'sessions',
              'watchdog' => 'watchdog',
            ),
            'utils_lock_tables' => 0,
            'use_mysqldump' => 0,
          ),
        ),
      ),
    )),
  );
}

/**
 * Implements hook_backup_migrate_schedules().
 */
function taz_core_backup_migrate_schedules() {
  return array(
    'daily' => backup_migrate_crud_create_item('schedule', array(
      'name' => 'Daily Backup',
      'source_id' => 'db',
      'destination_id' => 'scheduled',
      'profile_id' => 'default',
      'keep' => 90,
      'period' => 28800,
      'enabled' => 1,
      'cron' => 1,
    )),
    'snapshot' => backup_migrate_crud_create_item('schedule', array(
      'name' => 'Dev Snapshopt',
      'source_id' => 'db',
      'destination_id' => 'manual',
      'profile_id' => 'dev_snapshot',
      'keep' => 7,
      'period' => 43200,
      'enabled' => 1,
      'cron' => 1,
    )),
  );
}

/**
 * Implements hook_libraries_info().
 *
 * We declare all 3rd party libraries that we include that aren't already
 * declared by their corresponding modules.
 */
function taz_core_libraries_info() {
  $libraries = array();

  $libraries['jquery.coolinput'] = array(
    'name' => 'jQuery Coolinput',
    'vendor url' => 'https://github.com/alexweber/jquery.coolinput/',
    'download url' => 'https://github.com/alexweber/jquery.coolinput/archive/2.0.1.tar.gz',
    'library path' => drupal_get_path('profile', 'taz') . '/libraries/jquery.coolinput',
    'version arguments' => array(
      'file' => 'jquery.coolinput.js',
      'pattern' => '/@version\s+([0-9a-zA-Z\.-]+)/',
      'lines' => 5,
    ),
    'files' => array(
      'js' => array(
        'jquery.coolinput.min.js',
      ),
    ),
    'variants' => array(
      'minified' => array(
        'files' => array(
          'js' => array(
            'jquery.coolinput.min.js',
          ),
        ),
      ),
      'source' => array(
        'files' => array(
          'js' => array(
            'jquery.coolinput.js',
          ),
        ),
      ),
    ),
  );

  $libraries['jquery.hoverintent'] = array(
    'name' => 'jQuery HoverIntent',
    'vendor url' => 'http://cherne.net/brian/resources/jquery.hoverIntent.html',
    'download url' => 'http://cherne.net/brian/resources/jquery.hoverIntent.minified.js',
    'library path' => drupal_get_path('profile', 'taz') . '/libraries/jquery.hoverintent',
    'version arguments' => array(
      'file' => 'jquery.hoverIntent.minified.js',
      'pattern' => '/hoverIntent +([0-9a-zA-Z\.-]+)/',
      'lines' => 2,
    ),
    'files' => array(
      'js' => array(
        'jquery.hoverIntent.minified.js',
      ),
    ),
  );

  $libraries['jquery.scrollto'] = array(
    'name' => 'jQuery ScrollTo',
    'vendor url' => 'http://demos.flesler.com/jquery/scrollTo/',
    'download url' => 'https://github.com/flesler/jquery.scrollTo/archive/1.4.4.tar.gz',
    'library path' => drupal_get_path('profile', 'taz') . '/libraries/jquery.scrollto',
    'version arguments' => array(
      'file' => 'jquery.scrollTo-1.4.2-min.js',
      'pattern' => '/@version\s+([0-9a-zA-Z\.-]+)/',
      'lines' => 8,
    ),
    'files' => array(
      'js' => array(
        'jquery.scrollTo-1.4.2-min.js',
      ),
    ),
  );

  $libraries['jquery.easing'] = array(
    'name' => 'jQuery Easing',
    'vendor url' => 'http://gsgd.co.uk/sandbox/jquery/easing',
    'download url' => 'http://gsgd.co.uk/sandbox/jquery/easing/jquery.easing.1.3.js',
    'library path' => drupal_get_path('profile', 'taz') . '/libraries/jquery.easing',
    'version arguments' => array(
      'file' => 'jquery.easing.1.3.js',
      'pattern' => '/jQuery Easing v([0-9a-zA-Z\.-]+)/',
      'lines' => 2,
    ),
    'files' => array(
      'js' => array(
        'jquery.easing.1.3.js',
      ),
    ),
  );

  return $libraries;
}